version: '3.8'

services:
  sync-svc:
    hostname: sync-svc
    networks:
      - STT
    build:
      context: .
      dockerfile: ./controller/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /home/ec2-user/.aws:/root/.aws:ro 
networks:
  STT:
    driver: bridge
volumes:
  syncDBVolumn: